%General Mission Analysis Tool(GMAT) Script
%Created: 2023-10-08 23:27:55


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft FairDinkum;
GMAT FairDinkum.DateFormat = UTCGregorian;
GMAT FairDinkum.Epoch = '01 Jan 2000 11:59:28.000';
GMAT FairDinkum.CoordinateSystem = EarthMJ2000Eq;
GMAT FairDinkum.DisplayStateType = Keplerian;
GMAT FairDinkum.SMA = 12756;
GMAT FairDinkum.ECC = 0;
GMAT FairDinkum.INC = 24.99999999999999;
GMAT FairDinkum.RAAN = 0;
GMAT FairDinkum.AOP = 0;
GMAT FairDinkum.TA = 0;
GMAT FairDinkum.DryMass = 850;
GMAT FairDinkum.Cd = 2.2;
GMAT FairDinkum.Cr = 1.8;
GMAT FairDinkum.DragArea = 15;
GMAT FairDinkum.SRPArea = 1;
GMAT FairDinkum.SPADDragScaleFactor = 1;
GMAT FairDinkum.SPADSRPScaleFactor = 1;
GMAT FairDinkum.AtmosDensityScaleFactor = 1;
GMAT FairDinkum.ExtendedMassPropertiesModel = 'None';
GMAT FairDinkum.NAIFId = -10002001;
GMAT FairDinkum.NAIFIdReferenceFrame = -9002001;
GMAT FairDinkum.OrbitColor = Red;
GMAT FairDinkum.TargetColor = Teal;
GMAT FairDinkum.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT FairDinkum.CdSigma = 1e+70;
GMAT FairDinkum.CrSigma = 1e+70;
GMAT FairDinkum.Id = 'SatId';
GMAT FairDinkum.Attitude = CoordinateSystemFixed;
GMAT FairDinkum.SPADSRPInterpolationMethod = Bilinear;
GMAT FairDinkum.SPADSRPScaleFactorSigma = 1e+70;
GMAT FairDinkum.SPADDragInterpolationMethod = Bilinear;
GMAT FairDinkum.SPADDragScaleFactorSigma = 1e+70;
GMAT FairDinkum.AtmosDensityScaleFactorSigma = 1e+70;
GMAT FairDinkum.ModelFile = 'aura.3ds';
GMAT FairDinkum.ModelOffsetX = 0;
GMAT FairDinkum.ModelOffsetY = 0;
GMAT FairDinkum.ModelOffsetZ = 0;
GMAT FairDinkum.ModelRotationX = 0;
GMAT FairDinkum.ModelRotationY = 0;
GMAT FairDinkum.ModelRotationZ = 0;
GMAT FairDinkum.ModelScale = 1;
GMAT FairDinkum.AttitudeDisplayStateType = 'Quaternion';
GMAT FairDinkum.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT FairDinkum.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT FairDinkum.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn EarthTransferOrbitInsertion;
GMAT EarthTransferOrbitInsertion.CoordinateSystem = Local;
GMAT EarthTransferOrbitInsertion.Origin = Earth;
GMAT EarthTransferOrbitInsertion.Axes = VNB;
GMAT EarthTransferOrbitInsertion.Element1 = 0.865;
GMAT EarthTransferOrbitInsertion.Element2 = 0;
GMAT EarthTransferOrbitInsertion.Element3 = 0;
GMAT EarthTransferOrbitInsertion.DecrementMass = false;
GMAT EarthTransferOrbitInsertion.Isp = 300;
GMAT EarthTransferOrbitInsertion.GravitationalAccel = 9.81;

Create ImpulsiveBurn EarthFinalOrbitInsertion;
GMAT EarthFinalOrbitInsertion.CoordinateSystem = Local;
GMAT EarthFinalOrbitInsertion.Origin = Earth;
GMAT EarthFinalOrbitInsertion.Axes = VNB;
GMAT EarthFinalOrbitInsertion.Element1 = 0.725;
GMAT EarthFinalOrbitInsertion.Element2 = 0;
GMAT EarthFinalOrbitInsertion.Element3 = 0;
GMAT EarthFinalOrbitInsertion.DecrementMass = false;
GMAT EarthFinalOrbitInsertion.Isp = 300;
GMAT EarthFinalOrbitInsertion.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.2285714285714286 0.09414225941422594 ];
GMAT DefaultOrbitView.Size = [ 0.4149659863945578 0.3608786610878661 ];
GMAT DefaultOrbitView.RelativeZOrder = 197;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {FairDinkum, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ -30000 0 30000 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 3;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = X;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.580952380952381 0.02092050209205021 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.4156462585034014 0.3608786610878661 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 174;
GMAT DefaultGroundTrackPlot.Maximized = false;
GMAT DefaultGroundTrackPlot.Add = {FairDinkum};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate 'EarthParkingOrbit' DefaultProp(FairDinkum) {FairDinkum.Earth.Apoapsis, OrbitColor = [62 118 241]};
Maneuver 'Earth TOI' EarthTransferOrbitInsertion(FairDinkum);
Propagate 'EarthTransferOrbit' DefaultProp(FairDinkum) {FairDinkum.Earth.Apoapsis, OrbitColor = [100 240 158]};
Maneuver 'Earth FOI' EarthFinalOrbitInsertion(FairDinkum);
Propagate 'EarthFinalOrbit' DefaultProp(FairDinkum) {FairDinkum.ElapsedDays = 0.5, OrbitColor = [240 188 27]};
